name: jobs
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  get:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true